### ISSUE TITLE
sensiolabs insight issues

### ISSUE THREAD

**Issue by dbu** [symfony-cmf/routing-bundle#244]
sensiolabs insight is not too happy with this bundle: https://insight.sensiolabs.com/projects/58ca3dfe-0974-40b2-86cf-cd918fc92378/analyses/7

i am cleaning up the CS issues with namespaces and such. can we do anything sane about:
- the file inclusion in the bundle class? it seems a common practice to me to do locate files inside a bundle like this...
- the code duplication? (traits is not an option, we need to continue supporting php 5.3. static public method that we can call?)

**Comment by dbu** [comment]
a current report is https://insight.sensiolabs.com/projects/5529b865-12f1-42ec-b888-889efba1d3aa/analyses/1

@wouterj would you have an idea about how to include compiler passes without making insight be unhappy about it?

**Comment by wouterj** [comment]
I don't see any insight violations about compiler passes?

Op wo 15 feb. 2017 09:27 schreef David Buchmann <notifications@github.com>:

**Comment by dbu** [comment]
there is 7 violations of Absolute path constants __DIR__ and __FILE__ should not be used
```php
        $container->addCompilerPass(
            DoctrinePhpcrMappingsPass::createXmlMappingDriver(
                [
                    realpath(__DIR__.'/Resources/config/doctrine-model') => 'Symfony\Cmf\Bundle\RoutingBundle\Model',
```
