### ISSUE TITLE
Move contentTemplate to _contentTemplate

### ISSUE THREAD

**Issue by luishdez** [symfony-cmf/routing-bundle#252]
I'm using this bundle alone, with my own Route Provider 

First problem is that remaps _template to contentTemplate, so I can't use the initial FrameworkExtraBundle template functionality since the private default variable is always removed.

Second problem is that contentTemplate is a default without _ prefix so it's exposed if you generate paths from twig , so it creates:

**mypath/?contentTemplate=MyVendorBundle:Default:index.html.twig**

Not sure if there is an option to to disable the content Template mapping

**Comment by dbu** [comment]
@luishdez do you have time to work on this soonish? would love to include this in the next release we hope to cut in about 2 weeks.

**Comment by luishdez** [comment]
Oh boy! I totally forgot about this one. Apologies…

I'm traveling right now so it's a little bit complicated for me to complete this in 2 week, I'll be back next month If this is still pending I'll do it. ( added to my todo list so I won't forget… )

**Comment by dbu** [comment]
alright. its not in a big hurry, looking to your pull request in
september then. if we manage to do it fully BC we can even include it in
a patch version imho.
meanwhile, enjoy your travels :-)
