### ISSUE TITLE
Improve admin UX by removing options they don't care about

### ISSUE THREAD

**Issue by wouterj** [symfony-cmf/routing-bundle#285]
While doing the tab/group improvements, my eye's catched some options which I don't believe are usefull for the admin (at least not in the current way). I even believe most of them never will be usefull. First of all, words I don't think the admin understands: Controller, arguments, route.

If you then look closer at the options, the **Variable pattern** doesn't make any sense for the admin. What will change if the admin would put `something` in that text field? What's then passed to the "controller" (whatever that might be) if the controller defined those "arguments"?
What can the admin change with this? I think nothing.

The three checkboxes are about things I believe the admin understands (except that we should change "route" to "path" or "url" imo).
But then, if an admin checks **format pattern**, what is going to be changed? Does it mean the URL has to end with `.html`? If we want that, it should probably be a global option (it isn't very nice to edit every route in a website to enable/disable this).
The **trailing slash** is something that should be handled by the router itself imo. It's something the program has to care about, not the admin.

The **Compiler class** setting is the most cryptic of them all. Even I don't really know what it does. And if I know it, it would still not be usefull as it's just a plain text field. How do I know which compiler classes are available? I think this is an option that should only be provided to the developer.

At last, there are **Controller** and **Template** defaults. The first one belongs to the same group as the Compiler class imo. The **Template** class can be very usefull, it would allow the admin to change the theme for a page. However, we don't have anything about theming in our admin (we should maybe create a CmfThemingBundle). In the current way, there is no way to know what you can input in this field and what the page is going to look like in that case.

These are my thoughts about the routing admin, I would love to discuss this and see which options we can remove and what we can improve (e.g. adding a global settings page, a CmfThemingBundle, etc.)

**Comment by dbu** [comment]
i agree with your analysis more or less. i wonder if we should completely drop this, on the risk that somebody was using it, or if we just restrict it to a poweruser role that you can configure, that you can set to ROLE_USER if you do want to always see, but would default to ROLE_ADMIN_POWERUSER or something like that.

there are some that are more useful than others. the trailing slash is one of them, that might not be a global preference. controller is a really hacky way of mixing content with application. and template you would want to tune in your admin to only provide the list of templates that makes sense. (that depends on the target of the route actually, which is tricky). format pattern is likely a global option indeed.

variable pattern is most likely only useful through code, with the admin offering some checkboxes or dropdown to do things.

compiler class i have never seen a case where this needed to be configured in any symfony app.

i suggest we completely drop variable pattern and compiler class and limit the rest of the options you listed to the poweruser role. ok?

**Comment by WouterJ** [comment]
I propose the following plan:

* [ ] Remove *variable pattern* and *compiler class* settings
* [ ] Configure a role (defaults to `ROLE_ADMIN_POWERUSER`) for the *trailing slash*, *format pattern* and *controller* settings
* [ ] Improve the *template* setting to be a choice field with the available templates for the current content
* [ ] Create a way to have global settings (in CoreBundle) and move the *format pattern* setting to there

If you agree, I'll add them to this issue as task list, so we can start working on it.

**Comment by dbu** [comment]
good plan. some details (but we can continue discussion in respective issues if you don't agree/understand what i mean)

* for template: the default option should be to leave that empty. and this is a POWERUSER option as well i think. the UX will suck a bit that way, as you have to select target, save, and only then you see the available templates, and have to save again. but so be it.
* global setting: if we want global format pattern option we should put that into the routing bundle config if it does not already exist. we have other global things i think. there is no point in doing a admin for just this one thing - if anything we could do some sort of OptionAdmin that lets a user configure any configuration variables through the browser. (though in a sane cms, the devs want to do that in config, or the admin can break everything with a few mouse clicks)

**Comment by benglass** [comment]
@dbu @WouterJ I just came to this bundle to add an issue to make the configureFieldsForDefaults functionality more re-usable for other objects that implement route admin and need to be admined. I noticed you are talking about removing variable pattern but we actually use that in our admin class to allow advanced users (as you have said its based on an advanced role) to configure routes that need to have patterns like /user/{id} (bad example but you get the idea). I think you are saying that it wont make it so the controller knows to accept an id argument but I think thats fine since this is an advanced feature.

I think what I'm saying is can we move the route admin functionality to an admin extension to allow it to be used by other classes that extend route (like pages in a cms a la simplecms)?

**Comment by WouterJ** [comment]
@benglass you can extend this admin class for those admin functionality (like done in the simplecms bundle).

**Comment by benglass** [comment]
@WouterJ Yes that is an option but we wanted to avoid that as we didn't want any of the other functionality of the admin. It is similar to the concept of a MenuNodeAdmin that has lots of menu item related fields. There may be many classes that implement menu node and many that implement route and it would be ideal not to be forced to extend the parent class to get the admin functionality.

**Comment by dbu** [comment]
maybe the best way to go would be to build form types instead of tying oursevles to sonata admin, wherever possible. the form types would be much easier to reuse and extend in any context.

**Comment by benglass** [comment]
@dbu I like that idea in general as it starts to move us away from being so tied to sonata admin. we use sonata admin so its not a big deal i suppose but it doesnt seem ideal for situations like menu options, routing options, etc. where we already know of use cases where those fields would be re-used by multiple models

**Comment by dbu** [comment]
moved to https://github.com/symfony-cmf/sonata-phpcr-admin-integration-bundle/issues/74
