### ISSUE TITLE
Symfony 3.0 compatibility?

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony-cmf/routing-bundle#317]
I don't see this bundle in https://docs.google.com/spreadsheets/d/1GOxJ2lNpLxN12YyZ87Bhsxb0iLAQ7e4UDZbJSly8Sy8/edit#gid=0
Did someone try to make it Symfony compatible?

**Comment by dbu** [comment]
the Routing component is compatible: https://github.com/symfony-cmf/Routing/blob/master/composer.json#L17-L18

so i think it should not be too hard to make the bundle compatible as well. but i am not aware of ongoing work for that at the moment. might be something for the symfony con hackday this saturday.

**Comment by rande** [comment]
Checking now ;)

**Comment by killerwolf** [comment]
+1

**Comment by killerwolf** [comment]
+1 again :)

**Comment by dbu** [comment]
@killerwolf do you want to work on this? create a pull request where you adjust composer.json and the .travis.yml file to allow symfony 3 in addition to 2, then check if something fails and if so, check how to avoid the errors.

**Comment by killerwolf** [comment]
i'll try :) keep all of you updated soon

**Comment by killerwolf** [comment]
In progress here https://github.com/symfony-cmf/RoutingBundle/pull/323
Inputs are welcome

**Comment by killerwolf** [comment]
how to trigger travis build for this PR ?
styleci is yelling at me, is the [] shorthand mandatory ?

**Comment by killerwolf** [comment]
i found why..updated my fork, and every thing seems ok now

**Comment by dbu** [comment]
symfony 2.8 support is now merged in #326. for 3.0, we plan to work on a version 2.0 of this bundle that gets rid of all deprecated things and works with 2.8 and 3.x (see discussion in #324)

**Comment by WouterJ** [comment]
Closing, 2.0-dev is now compatible with Symfony 3.x
