### ISSUE TITLE
Route endpoint to mark as a collection

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony-cmf/routing-bundle#350]
As a collection can be one representation of resource in a REST world. I would like to see either a CollectionRoute or a marker like `_template`, .. to make a route to such a collection route. This collection route would open a door for an POST restenpoint. For POST i don't have a contentDocument, as i want to create it.
Such a collection can come together with an collection "document" type to render list of collection as it is done for the container in block-bundle. This can be a little tricky for html representation, but it is very common json and xml.

**Comment by dbu** [comment]
if you want to create new documents with POST, you probably also want to create new cmf routes for them. in that case you need a statically configured route to post to to create new documents - that fixed end point does not need to be in the cmf, its an application level thing and not an editor thing.
or you could use some sort of "404 handler" that detects i want to create the route that was not yet existing.
