### ISSUE TITLE
Add all scenarios for route i18n

### ISSUE THREAD

**Issue by hason** [symfony-cmf/routing-bundle#352]
This bundle supports prefixing all routes with locale. It would be perfect if it adopts all scenarios from [JMSI18nRoutingBundle](http://jmsyst.com/bundles/JMSI18nRoutingBundle/master/configuration):
1. Scenario: Prefixing All Routes With The Locale
2. Scenario: Prefixing All Routes With The Locale except those of the default locale
3. Scenario: Using different hosts for each locale
4. Scenario: Something Else

**Comment by dbu** [comment]
I think we have pretty much all of that:

1. You can store routes under a locale prefix, like /cms/routes/en and /cms/routes/de. There is a listener that sets the request locale based on the locale prefix.
2. You can store routes under /cms/routes directly and they will use the default locale if there is none set from somewhere else
3. You can use different hosts and likely would use /cms/routes/en-host|de-host to store the routes. I am not sure if expression language or anything would already allow to set the right base path based on the host name or if we need something extra for this scenario. maybe write a variant of https://github.com/symfony-cmf/routing-bundle/blob/master/Doctrine/Phpcr/PrefixCandidates.php#L103 that is DomainCandidates or something?
4. ?

i am not sure how much we need to build this into the bundle or if its more a cookbook entry in the documentation to explain how to do each of the scenarios.
