### ISSUE TITLE
Using this bundle for dynamic host condition?

### ISSUE THREAD

**Issue by winzou** [symfony-cmf/routing-bundle#354]
Hello,

I'm having a hard time to see if this bundle can fit my specific need. Let me explain.

I have a website that can have different content depending on the host. So if you come on `siteA.com`, I will show you all entities X filtered by `siteA`. If you come on `siteB.com`, the structure will be the same (same route, same controller), but again I will show you entities X filtered by `siteB`

I have already all Doctrine filters up and running to filter my entities. But my question is on the routing side. If everything was static, I could do:

```
fox:
    resource: "@FoxBundle/Resources/config/routing.yml"
    host: 'siteA.com|siteB.com'
```

But the thing is that I have many sites (registered as an entity), and these are dynamic (I can disable/enable them).

Would CMFRoutingBundle fit this use case? And if so, how?

Thanks for your help!

**Comment by dbu** [comment]
the cmf routing bundle provides a route provider that talks to doctrine to find possible routes for a request. and it provides a base Route orm entity / phpcr document that extend the symfony core route object and define mappings. the requirements are persisted, so you can let your code generate routes and add requirements on the host.

if you use phpcr-odm, you can also use another idea: use multiple base paths to have one tree of routes per site, and another default tree. use expression language to configure the base paths to have the right path for the requested domain.
