### ISSUE TITLE
how to link in body of document to other document

### ISSUE THREAD

**Issue by maity-kgz** [symfony-cmf/routing-bundle#364]
For example in admin panel while editing some document I want to link to other document in body of current document. Is it possible ?

**Comment by dbu** [comment]
there is no plugin for this. we experimented with [embedding blocks](http://symfony.com/doc/current/cmf/bundles/block/introduction.html#embedding-blocks-in-wysiwyg-content) which works unless you have frontend editing or a wysiwyg editor.

we described a generalization idea here https://github.com/symfony-cmf/symfony-cmf/wiki/Future-ideas#extensible-way-to-embed-dynamicservice-based-content-into-phpcr-fields (but that has the same issue as with the block filter that the editor is aware of it and it does not play well with wysiwyg)

for linking content, we discussed the idea to use custom html attributes to track the uuid of the target (in a doctrine listener, scan body for `<a>` that have an internal href and update content on writing) and remove the extra ids when outputting to the frontend (and checking if link url target is still right and if not change the url if the uuid still is found, probably in a twig filter). such a feature would probably operate on the cmf route objects as those are in the end the things that have urls. we have not planned to work on this anytime soon, but if you want to take up the task, we are happy for a pull request.
