### ISSUE TITLE
Meaning and usage of variable "position"

### ISSUE THREAD

**Issue by equimed** [symfony-cmf/routing-bundle#365]
The ORM version of Route.php defines a variable called position. I don't understand the usage of this variable. Please clarify.

**Comment by dbu** [comment]
okay, the dock on the Doctrine\Orm\Route class is rather lacking...

the position is used in the Doctrine\Orm\RouteProvider class to sort
potential routes by that field, ascending. this defines precedence in
case several routes would match for a request. this is relevant when one
route defines a pattern like /foo/{parameter} and one route is
/foo/specific-thing . the specific route needs to come before the
general one, or the general one will hide the specific one.

glad if you want to improve the phpdoc or write some things in the
symfony-cmf-docs on the orm route implementation (it seems the
symfony-cmf-docs explains the phpcr-odm document a bit at
http://symfony.com/doc/current/cmf/book/routing.html#the-phpcr-odm-route-document
but the only thing on orm is in
http://symfony.com/doc/current/cmf/bundles/routing/dynamic.html#doctrine-orm-integration
and very limited)
