### ISSUE TITLE
Tagging version allowing Symfony 3.+ 

### ISSUE THREAD

**Issue by TomasVotruba** [symfony-cmf/routing-bundle#366]
Symfony 3 has been there for almost a year (in this package), yet there is no tagger version.
I want to use this package as dependency in other package and with Symfony 3.

This would really help me. I'm wondering, what is the blocker here?

**Comment by pamil** [comment]
Same here 🐫

**Comment by killerwolf** [comment]
+1

**Comment by dbu** [comment]
this is the list where we coordinate to make the release happen: https://github.com/symfony-cmf/symfony-cmf/issues/235#issuecomment-263077327

if all that +1 here help with one or to pull requests, that would be a great help

**Comment by dbu** [comment]
yay, i just tagged 2.0.0! with symfony 2.8 and 3.* support. please see the changelog and upgrade instructions.

**Comment by TomasVotruba** [comment]
Finally, thank you! :+1:
