### ISSUE TITLE
Symfony 3.2 support/bug ?

### ISSUE THREAD

**Issue by sandergo90** [symfony-cmf/routing-bundle#370]
Hi,

We our the creators of the KunstmaanBundlesCMS for symfony. We are using the symfony-cmf/routing-bundle in our standard edition and we are trying to upgrade now to symfony 3.2. 

But, we have some issues.

When we update to symfony 3.2 we get the following exception:

Interface 'Doctrine\ODM\PHPCR\HierarchyInterface' not found in /home/projects/willfeed/data/willfeed/vendor/symfony-cmf/routing-bundle/Doctrine/Phpcr/Route.php on line 27

That's indeed correct because we do not install the the doctrine-odm package. But in previous symfony versions, this works and we do not get a error there. I think the problem is that as of symfony 3.2 all the classes are automatically warmed up for caching purposes. Therefor symfony will also pass by the Symfony\Cmf\Bundle\RoutingBundle\Doctrine\Phpcr\Route class and will find an interface there that does not exists.

Can you guys take a look at this, or correct me if we are doing something wrong?

Cheers!

**Comment by n-sviridenko** [comment]
+1

**Comment by ElectricMaxxx** [comment]
hi, 
thanks for reporting that issue. Tried to get your error just by adding more versions to our travisCI tests, 
https://travis-ci.org/symfony-cmf/routing-bundle/builds/180687956
but i become other issues then yours. So other question: Which other What is your version of the phpcr-odm? Maybe you can post the cmf relevant parts of the composer.json

**Comment by sandergo90** [comment]
Hi,

The problem occurs when warming up the cache but your test suite exits already before doing this. We are using the dev-master of symfony-cmf/routing and symfony-cmf/routing-bundle.

Cheers

**Comment by sandergo90** [comment]
@ElectricMaxxx right now i have added this to my composer.json file

 "autoload": {
        "psr-4": { "": "src/" },
        "classmap": [ "app/AppKernel.php", "app/AppCache.php" ],
        "exclude-from-classmap": [
            "vendor/symfony-cmf/routing-bundle/Doctrine/Phpcr/Route",
            "vendor/symfony-cmf/routing-bundle/Doctrine/Phpcr/RedirectRoute"
        ]
    },

This way the autoloader will not process this files. The problem actually comes from the new Symfony\Bundle\FrameworkBundle\CacheWarmer\ValidatorCacheWarmer that is invokes with the cache:warmup. It will check all the validation.xml files. And in the routing bundle there is a validation.xml file who references this two classes of Route and RedirectRoute. My solution is not the way it should be done in the bundle itself, but right now for me it's a solution that works ;)

**Comment by ElectricMaxxx** [comment]
yea i would say that isn't a bug anymore as we currently support until Symfony 2.8. But and i hope @dbu @wouterj will be the same opinion, that we should support until 3.2 when we releas a 2.0. But we should discuss what to support on https://github.com/symfony-cmf/symfony-cmf/issues/235

**Comment by dbu** [comment]
i am not sure how we will have to handle this. is there a way to register validation configuration conditionally? or to interact with the ValidatorCacheWarmer so our DI extension/a compiler pass can tell it to skip that folder if phpcr-odm is not installed?

**Comment by sandergo90** [comment]
In my opinion you should Move the code for phpcr to another bundle maybe ? Using an interface that only exists when another bundle is installed looks a bit ugly, not ?

**Comment by ElectricMaxxx** [comment]
At least the calling code has to respect when phcr isn't used as persistence. Otherwise the file should exist.

**Comment by sandergo90** [comment]
Yes the ValidatorCacheWarmer checks if a class exists so this is correct but it does and can not check if the class that exists has interfaces that do not exisit.

**Comment by wouterj** [comment]
I think we can fix this in a compiler pass. At the moment, we're using a `validation.xml` file, which is [loaded automatically](https://github.com/symfony/framework-bundle/blob/master/DependencyInjection/FrameworkExtension.php#L962-L1000).

We can change this to have seperate `validation_phpcr.xml`, `validation_orm.xml`, etc files. Then, inside a compiler pass, we can do `$validatorBuilder->addMethodCall('addXmlMappings', array(__DIR__.'../../Resources/config/validation_phpcr.xml'));` if PHPCR is enabled. This means that if PHPCR is disabled, the validation metadata is no longer loaded and the error should not be there.

**Comment by wouterj** [comment]
We should btw also check other bundles for this. We added some validations to fix SonataAdmin incompatibility issues. IIRC, at least the BlockBundle uses validation.

**Comment by sandergo90** [comment]
Thanks for the fix guys! It works now ;)

Cheers
