### ISSUE TITLE
Set roothPath (content and route) based on different path

### ISSUE THREAD

**Issue by ilijastojkovic** [symfony-cmf/routing-bundle#391]
Default idPrefix prefix is **/cms/routes/**, is possible to re-set default path to:
i.e.
**/path1/cms/routes/
/path2/cms/routes/
/path3/cms/routes/**

contentRootPath is possible to changed (**/path1/cms/content/**, **/path2/cms/content/** ... ), but is possible to change default rootPath of routes?

**Comment by dbu** [comment]
you can configure a list of root paths for routes. the router will then look at all those locations. you can also use the expression language in the configuration to set the root path, if that helps you. 

last, you can do a compiler pass or symfony event listener (as long as the listener happens before routing) that takes PrefixCandidates from the service `cmf_routing.phpcr_candidates_prefix` and calls addPrefix resp setPrefixes on it.
