### ISSUE TITLE
Generating route for newly created page

### ISSUE THREAD

**Issue by silverbackdan** [symfony-cmf/routing-bundle#394]
I am trying to generate a route to a newly created page so that I can redirect a user there. This is the script I am trying to make work:
```php
        $documentManager = $this->get('doctrine_phpcr')->getManager();
        $rootPage = $documentManager->find(null, $rootDocId);
        $newDoc->setParentDocument($rootPage);
        $documentManager->persist($newDoc);
        $documentManager->flush();
        $newUrl = $this->get('cmf_menu.content_router')->generate(
            $newDoc,
            [],
            true
        );
```
Fora newly created page, this does not appear to work. I imagine because when this route is loaded, the other dynamic routes have already been created too. Is there a function to refresh the CMF chain router so I can send the URL for the newly created page back to a front-end?

**Comment by dbu** [comment]
hm, generating a route should work even if its not persisted, if you pass an object to the route generator. are you sure that $newDoc is a Route, or implements the RouteAware interface and has a route set on it? what does the exception say exactly?

**Comment by silverbackdan** [comment]
It's strange because I can run the exact same code on the same document on a new request and it will work. The error is:
`None of the chained routers were able to generate route: Route 'Route aware content DataBundle\\Document\\NewsPost' not found`
The doc implements `Symfony\Cmf\Component\Routing\RouteReferrersReadInterface`

**Comment by silverbackdan** [comment]
For the sake of transparent, this is more relevant code:

**The PHPCR document class**
```php
<?php

namespace DataBundle\Document;

use Doctrine\ODM\PHPCR\Mapping\Annotations as PHPCR;
use Knp\Menu\NodeInterface;
use Symfony\Cmf\Component\Routing\RouteReferrersReadInterface;

/**
 * @PHPCR\Document(referenceable=true)
 */
class NewsPost implements RouteReferrersReadInterface, NodeInterface
{
    use BaseContentTrait;
    use KnpMenuNodeInterfaceTrait;

    /**
     * @PHPCR\Field(type="boolean")
     */
    protected $live = false;

    /**
     * @PHPCR\Date(nullable=true)
     */
    protected $liveDate;

    /**
     * @return boolean
     */
    public function getLive()
    {
        return $this->live;
    }

    /**
     * @param boolean $live
     */
    public function setLive($live)
    {
        $this->live = $live;
        if (!$this->liveDate && $this->live) {
            $this->liveDate = new \DateTime();
        }
    }

    /**
     * @return mixed
     */
    public function getLiveDate()
    {
        return $this->liveDate ?: $this->date;
    }

    public function getSlug()
    {
        return $this->slug ?: $this->header ?: $this->label ?: $this->name;
    }

    public function getHeader()
    {
        return $this->header ?: $this->label ?: $this->name;
    }

    public function getLabel()
    {
        return $this->header ?: $this->label ?: $this->name;
    }
}
```

I can include the traits if you'd like, but I'd have an error if I wasn't implementing all the required methods as I'm using PHPStorm. Nevertheless, I think all the required methods are in my BaseContentTrait as seen here:
```php
<?php

namespace DataBundle\Document;

use Doctrine\ODM\PHPCR\Mapping\Annotations as PHPCR;

trait BaseContentTrait
{
    /**
     * @PHPCR\Id()
     */
    protected $id;

    /**
     * @PHPCR\Date()
     */
    protected $date;

    /**
     * @PHPCR\Date()
     */
    protected $lastUpdated;

    /**
     * @PHPCR\ParentDocument()
     */
    protected $parent;

    /**
     * @PHPCR\Field(type="string", nullable=true)
     */
    protected $body;

    /**
     * @PHPCR\Referrers(
     *     referringDocument="Symfony\Cmf\Bundle\RoutingBundle\Doctrine\Phpcr\Route",
     *     referencedBy="content"
     * )
     */
    protected $routes;

    /**
     * @PHPCR\Field(type="string", nullable=true)
     */
    protected $header = null;

    /**
     * @PHPCR\Field(type="string", nullable=true)
     */
    protected $metaDescription = null;

    public function getId()
    {
        return $this->id;
    }

    public function getDate()
    {
        return $this->date;
    }

    /**
     * @PHPCR\PrePersist()
     */
    public function setDate()
    {
        $this->date = new \DateTime();
    }

    /**
     * @return mixed
     */
    public function getLastUpdated()
    {
        return $this->lastUpdated;
    }

    /**
     * @PHPCR\PreUpdate()
     * @PHPCR\PrePersist()
     */
    public function setLastUpdated()
    {
        $this->lastUpdated = new \DateTime();
    }

    public function getParentDocument()
    {
        return $this->parent;
    }

    public function setParentDocument($parent)
    {
        $this->parent = $parent;
    }

    public function getBody()
    {
        return $this->body;
    }

    public function setBody($body)
    {
        $body = preg_replace( "/\r|\n/", '', $body);
        $this->body = $body;
    }

    public function getRoutes()
    {
        return $this->routes;
    }

    public function getHeader()
    {
        return $this->header;
    }

    public function setHeader($header)
    {
        $this->header = $header;
    }

    /**
     * @return string
     */
    public function getMetaDescription()
    {
        return $this->metaDescription;
    }

    /**
     * @param string $metaDescription
     */
    public function setMetaDescription($metaDescription)
    {
        $this->metaDescription = $metaDescription;
    }

    /**
     * @return string
     */
    public function getRealMetaDescription()
    {
        return $this->metaDescription ?: explode('. ', substr(strip_tags($this->body), 0, 160))[0];
    }
}
```

When I add a NewsPost it uses these methods
```php
public function postNewsAction () {
        $newsItem = new NewsPost();
        $newsItem->setName('news-'.strtotime('now'));
        $newsItem->setHeader('**New**');
        return $this->postDocument('/cms/pages/home/news', $newsItem);
    }
private function postDocument ($rootDocId, $newDoc) {
        $documentManager = $this->get('doctrine_phpcr')->getManager();
        $rootPage = $documentManager->find(null, $rootDocId);
        $newDoc->setParentDocument($rootPage);
        $documentManager->persist($newDoc);
        $documentManager->flush();

        $newUrl = null; //$this->get('cmf_menu.content_router')->generate($newDoc, [], true);
        return $this->view(['success' => true, 'data' => $newDoc, 'newUrl' => $newUrl], Response::HTTP_CREATED);
    }
```
I've commented out the new URL as it returns the error I gave before.

I imagine it's something silly I've done from your first comment saying it should work, but I haven't been able to figure out what it is just yet.

**Comment by silverbackdan** [comment]
Oh and cmf_routing_auto.yml
```yaml
DataBundle\Document\GenericPage:
    definitions:
        main:
            uri_schema: /{slug}
    token_providers:
        slug: [content_method, { method: getSlug }]
    conflict_resolver: auto_increment

DataBundle\Document\NewsPost:
    definitions:
        main:
            uri_schema: /news/{date}/{header}
    token_providers:
        header: [content_method, { method: getHeader }]
        date: [content_datetime, { method: getLiveDate, date_format: 'F-Y' }]
    conflict_resolver: auto_increment
```

**Comment by silverbackdan** [comment]
OK, little progress - so $newDoc->getRoutes() is an empty array. When loading the same doc on a new page, this is a ReferrersCollection

baby steps :P

**Comment by silverbackdan** [comment]
So with the help of your comment telling me to look at if the doc has a route set on it, I found https://github.com/doctrine/phpcr-odm/issues/621 - I'll just refresh it `$documentManager->refresh($newDoc);` works a charm. Sorry for monstrously long comments. As always, I hope it ends up helping someone else (although in this instance I doubt it).

**Comment by dbu** [comment]
a classic example of rubberducking ;-D glad you found the solution.

but from what you say, it sounds like routing auto does not set the back reference to the new route on the document that is routed. i would consider that a bug of routing-auto. the route points to the content. the content has a referrer mapping to know what routes point *to* it. if only the route with the reference is stored, the referrer is indeed not automatically updated without refresh / new request.

this seems a bug of routing auto. it should check if the content being routed implements the full RouteAwareInterface and if so call `addRoute` on it - see https://github.com/symfony-cmf/routing/blob/d4fa611c200b47f81031dd34adc96ed5ed4c087c/src/RouteReferrersInterface.php#L27

do you want to send a bugfix pull request to routing-auto for this?

**Comment by silverbackdan** [comment]
:P I'll rise an issue first because I don't have a lot of time right now to investigate and figure out a potential solution - someone who knows it may work it out very quickly, but I'll reference this issue too. I'll see if I can look into a better solution when I get a mo, Thanks @dbu !

**Comment by dbu** [comment]
oh, if your content does not implement the interface, then its entirely your fault :-P can you check that? if it does not, the only question that remains is whether we can improve the documentation to prevent others from running into the same gotcha...

can you please open the issue on symfony-cmf/routing-auto ?

**Comment by silverbackdan** [comment]
It implements `RouteReferrersReadInterface` which doesn't include the `addRoute` method but routes should be auto-generated. I'm quite confused as to what I'd put in the `addRoute` method so I'll raise the issue there right now. Thanks @dbu
