### ISSUE TITLE
Non-existent service "validator.builder"

### ISSUE THREAD

**Issue by damienflament** [symfony-cmf/routing-bundle#413]
#### Symfony packages

```
$ composer show 'symfony/*'

symfony/cache                v4.0.2
symfony/class-loader         v3.4.3
symfony/config                v4.0.2
symfony/console              v4.0.2
symfony/debug                v4.0.2
symfony/dependency-injection v4.0.3
symfony/doctrine-bridge      v4.0.3
symfony/dotenv               v4.0.2
symfony/event-dispatcher     v4.0.2
symfony/filesystem            v4.0.2
symfony/finder                v4.0.2
symfony/flex                  v1.0.57
symfony/framework-bundle     v4.0.2
symfony/http-foundation      v4.0.2
symfony/http-kernel          v4.0.2
symfony/options-resolver     v4.0.3
symfony/polyfill-mbstring     v1.6.0
symfony/process              v4.0.2
symfony/routing              v4.0.2
symfony/translation          v4.0.3
symfony/twig-bridge          v4.0.2
symfony/twig-bundle          v4.0.2
symfony/web-server-bundle    v4.0.2
symfony/yaml                 v4.0.2
```

#### Symfony CMF packages

```
$ composer show 'symfony-cmf/*'

symfony-cmf/routing             dev-master e1bc515
symfony-cmf/routing-auto        dev-master 12a71fa
symfony-cmf/routing-auto-bundle dev-master ab9fa1d
symfony-cmf/routing-bundle      dev-master 77a6ece
symfony-cmf/slugifier-api        2.0.0
```

## Subject
The bundle is used in a Symfony 4 Flex application.

I tried to reproduce this behavior using the bundle tests, but didn't succeed.

I think this is due to [the `ValidationPass` trying to get the `validation.builder` service](https://github.com/symfony-cmf/routing-bundle/blob/6587c42b8ca3a07d7dc41cb6ee10d8d812c8163d/src/DependencyInjection/Compiler/ValidationPass.php#L26) which [is private](https://github.com/symfony/framework-bundle/blob/82e45a486a2cbdab5d43512bea10af1681dcd8e2/Resources/config/validator.xml#L13).

Can you confirm ?

## Steps to reproduce
Run the Symfony console.

```
bin/console -vvv
```

## Expected results
The console application runs.

## Actual results

```
In ContainerBuilder.php line 972:

  [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
  You have requested a non-existent service "validator.builder".


Exception trace:
 Symfony\Component\DependencyInjection\ContainerBuilder->getDefinition() at %root%/vendor/symfony-cmf/routing-bundle/src/DependencyInjection/Compiler/ValidationPass.php:26
 Symfony\Cmf\Bundle\RoutingBundle\DependencyInjection\Compiler\ValidationPass->process() at %root%/vendor/symfony/dependency-injection/Compiler/Compiler.php:95
 Symfony\Component\DependencyInjection\Compiler\Compiler->compile() at %root%/vendor/symfony/dependency-injection/ContainerBuilder.php:707
 Symfony\Component\DependencyInjection\ContainerBuilder->compile() at %root%/vendor/symfony/http-kernel/Kernel.php:504
 Symfony\Component\HttpKernel\Kernel->initializeContainer() at %root%/vendor/symfony/http-kernel/Kernel.php:125
 Symfony\Component\HttpKernel\Kernel->boot() at %root%/vendor/symfony/framework-bundle/Console/Application.php:63
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at %root%/vendor/symfony/console/Application.php:143
 Symfony\Component\Console\Application->run() at %root%/bin/console:39
```

**Comment by damienflament** [comment]
After some research, it appears that the `validator.builder` service is registered by the _FrameworkBundle_ [only when the `framework.validation` configuration is enabled](https://github.com/symfony/framework-bundle/blob/82e45a486a2cbdab5d43512bea10af1681dcd8e2/DependencyInjection/FrameworkExtension.php#L955).

But the Symfony _Validator_ component is optional for the _FrameworkBundle_.

So, the _RoutingBundle_ needs the `symfony/validator` component.

How to deal with that ?
 1. Make the `Route` and `RedirectRoute` documents validation optional (depending on the availability of the `validator.builder` service) OR
 2. Require the `symfony/validator` component AND:
   a. enable the Symfony validation while compiling the container OR
   b. specify in the documentation that the `framework.validation.enabled` configuration must be set to `true` ?

**Comment by dbu** [comment]
we do not need the validator, its more that we add some validation files if it is active already. do we ourselves actively validate the route somewhere in this bundle? i think not - and if we don't then the correct change is 1), to skip if the validator service is not around. i guess we can just check the container for the validator service and return early if its missing. want to do a pull request for that?

**Comment by damienflament** [comment]
After some further research, the `framework.validation` configuration was enabled by default. That's why this bug wasn't discovered.

But [a recent commit changed this behavior](https://github.com/symfony/framework-bundle/commit/228bb29bc79dd8b3ebecc2a2210a86a962070171).

@dbu I will do a PR.
