### ISSUE TITLE
Improve tests

### ISSUE THREAD

**Issue by damienflament** [symfony-cmf/routing-bundle#415]
I just caught [a typo](https://github.com/symfony-cmf/routing-bundle/blob/bbcd14995e030ec0b10641241da3e3bc7972d4b9/src/DependencyInjection/Compiler/ValidationPass.php#L24) in [my last PR](https://github.com/symfony-cmf/routing-bundle/pull/414).

The tests run succeeded.

They need some improvements.

**Comment by dbu** [comment]
fixed in #416
