### ISSUE TITLE
Jackrabbit error when the URL has a leading or trailing space

### ISSUE THREAD

**Issue by UFTimmy** [symfony-cmf/routing-bundle#430]
Howdy,

If the URL entered by the user has a leading or trailing space then Jackrabbit produces an error. An example URL that produces an error is `/could-be-anything%20` or `/%20could-be-anything`. Note that spaces in the middle of the URL are fine.

Then when the Jackrabbit Request object tries to parse what came back from the server via loadXml, it produces the following error:

`Warning: DOMDocument::loadXML(): AttValue: &quot; or ' expected in Entity, line: 1`

This is the same error message as #259 .

I'm not positive I am reporting the error to the correct package, but since this has the same error message as the previous one I am reporting it here. If it belongs somewhere else, please let me know.

I am going to work around this issue by creating a high priority Kernel listener that detects leading and trailing spaces and removes them.

Here is what the Jackrabbit server sends back in the Request object: 

```<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<nodeTypes>
    <nodeType hasOrderableChildNodes="true" isAbstract="false" isMixin="false" isQueryable="true" name="nt:unstructured">
        <supertypes>
            <supertype>nt:base</supertype>
        </supertypes>
        <childNodeDefinition autoCreated="false" declaringNodeType="nt:unstructured" defaultPrimaryType="nt:unstructured" mandatory="false" name="*" onParentVersion="VERSION" protected="false" sameNameSiblings="true">
            <requiredPrimaryTypes>
                <requiredPrimaryType>nt:base</requiredPrimaryType>
            </requiredPrimaryTypes>
        </childNodeDefinition>
        <propertyDefinition autoCreated="false" declaringNodeType="nt:unstructured" fullTextSearchable="true" mandatory="false" multiple="false" name="*" onParentVersion="COPY" protected="false" queryOrderable="true" requiredType="undefined">
            <valueConstraints />
            <availableQueryOperators>
                <availableQueryOperator>jcr.operator.equal.to</availableQueryOperator>
                <availableQueryOperator>jcr.operator.not.equal.to</availableQueryOperator>
                <availableQueryOperator>jcr.operator.greater.than</availableQueryOperator>
                <availableQueryOperator>jcr.operator.greater.than.or.equal.to</availableQueryOperator>
                <availableQueryOperator>jcr.operator.less.than</availableQueryOperator>
                <availableQueryOperator>jcr.operator.less.than.or.equal.to</availableQueryOperator>
                <availableQueryOperator>jcr.operator.like</availableQueryOperator>
            </availableQueryOperators>
        </propertyDefinition>
        <propertyDefinition autoCreated="false" declaringNodeType="nt:unstructured" fullTextSearchable="true" mandatory="false" multiple="true" name="*" onParentVersion="COPY" protected="false" queryOrderable="true" requiredType="undefined">
            <valueConstraints />
            <availableQueryOperators>
                <availableQueryOperator>jcr.operator.equal.to</availableQueryOperator>
                <availableQueryOperator>jcr.operator.not.equal.to</availableQueryOperator>
                <availableQueryOperator>jcr.operator.greater.than</availableQueryOperator>
                <availableQueryOperator>jcr.operator.greater.than.or.equal.to</availableQueryOperator>
                <availableQueryOperator>jcr.operator.less.than</availableQueryOperator>
                <availableQueryOperator>jcr.operator.less.than.or.equal.to</availableQueryOperator>
                <availableQueryOperator>jcr.operator.like</availableQueryOperator>
            </availableQueryOperators>
        </propertyDefinition>
    </nodeType>
</nodeTypes>

**Comment by dbu** [comment]
hi, hm this does look like something goes wrong somewhere. what do you mean by "entered by the user"? #259 was about web requests. but what you describe sounds like there is some sort of admin interface involved? is it about sonata admin when putting / into the "Name" text field in the document location? i tried to reproduce the problem [there](http://sandbox.cmf.symfony.com/en/admin/app/demoseocontent/create?tl=en) but get `an error has occured during the creation of "test page"` if i give the name as `/test`. this is not great error handling, the admin should not allow the `/` in the name and tell the user about the problem.

are you using jackalope-jackrabbit, or jackalope-doctrine-dbal? and can you try to find the xml data that contains the encoded character and is invalid xml? what you copied is a different request that shows the node types. maybe try-catch the DOMDocument exception and dump what it tried to parse only when the exception happens?

**Comment by UFTimmy** [comment]
Entered by the user means they enter that URL into their browser. It means that the Routing bundle tries to match the URL entered by the user to a set of documents.

It looks like the Routing component creates a list of possible nodes and tries to fetch them, and if that list of possible nodes contains a leading or trailing space, Jackrabbit dies. Example bad URLs:

/path/%20to/page
/path%20/to/page
/path/to/page%20
/%20/path/to/page

I will find the bad XML in a little bit once I am at work.

**Comment by UFTimmy** [comment]
The error happens when the RouteProvider tries to find candidates. Here is an example of its candidate pool:

```
array (
  '/cms/sites/XXX/routes/cms/frontEnd/about ' => '/cms/sites/XXX/routes/cms/frontEnd/about ',
  '/cms/sites/XXX/routes/cms/frontEnd' => '/cms/sites/XXX/routes/cms/frontEnd',
  '/cms/sites/XXX/routes/cms' => '/cms/sites/XXX/routes/cms',
  '/cms/sites/XXX/routes' => '/cms/sites/XXX/routes',
)
```

You can see the space at the end of the top candidate. It's basically kicking off an ObjectManager::getNodes()

Request::singleRequest sends the CURL request, and gets back a 500 status code. The content of the error that it receives back is not helpful:

```
<html><head><title>Apache Tomcat/7.0.68 (Ubuntu) - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif
```

It's at that point it kicks off the call to getRepositoryDescriptors to see if the backend Jackrabbit is a supported version.

Here is a screen shot of the trace of getting to that point, if it helps:
https://i.imgur.com/UAwbqyT.png

**Comment by dbu** [comment]
okay, thats not elegant. from how i read https://docs.adobe.com/docs/en/spec/jcr/2.0/3_Repository_Model.html#3.2.2%20Local%20Names i would assume that whitespace in node names should be legal. they do say

> These restrictions are not necessarily sufficient to enforce best practices in the creation of JCR names. In particular, the minimal grammar defined here permits JCR names with leading and trailing whitespace as well as characters which may appear superficially identical while representing different code points, creating a potential security issue.

but it sounds to me like a bug in the jackrabbit communication protocol. we seem to [urldecode here](https://github.com/symfony-cmf/routing-bundle/blob/ed21276d9fe1599518bc6e9576e53ae84b816da3/src/Doctrine/Phpcr/PrefixCandidates.php#L106) which gives us actual whitespace rather than %20. that could create problems with other characters, notably %2F (`/`) at the start or end of a segment. we seem to [filter out those already](https://github.com/symfony-cmf/routing-bundle/blob/ed21276d9fe1599518bc6e9576e53ae84b816da3/src/Doctrine/Phpcr/PrefixCandidates.php#L119)

could you do a pull request to add a check for trailing whitespace in [this loop](https://github.com/symfony-cmf/routing-bundle/blob/ed21276d9fe1599518bc6e9576e53ae84b816da3/src/Doctrine/Phpcr/PrefixCandidates.php#L119-L124) ? along with a unit test that verifys we indeed filter them out correctly. 

what works and what does not?
* `/ foo`
* `/fo o`
* `/foo `
* `/foo /bar` (when we build candidates, one will be `/foo `, but does the candidate with "bar" at the end also fail?

**Comment by UFTimmy** [comment]
It turns out that that square brackets (both `[` and `]`) are also disallowed and produce errors.

So your bad characters are space, left square bracket, and right square bracket.

The rules that I have discovered is that these characters cannot appear:

1. At the end of the path
2. Immediately before a slash in the path.
3. Immediately after a slash in the path.

So from your example:

`/ foo` fails because the space follows the slash
`/fo o` is valid because the space is neither adjacent to a slash, or at the end of the path
`/foo` is valid, no space
`/foo /bar` will fail because the space precedes the slash.

Here is an example of the body of a getPaths request with a space in it:

The URL entered into the browser is `/fire /test`. The route prefix is `/cms/sites/Site Name/routes/cms/frontEnd/`

```
%3Ainclude=%2Fcms%2Fsites%2FSite+Name%2Froutes%2Fcms%2FfrontEnd%2Ffire+%2Ftest&%3Ainclude=%2Fcms%2Fsites%2FSite+Name%2Froutes%2Fcms%2FfrontEnd%2Ffire+&%3Ainclude=%2Fcms%2Fsites%2FSite+Name%2Froutes%2Fcms%2FfrontEnd&%3Ainclude=%2Fcms%2Fsites%2FSite+Name%2Froutes%2Fcms&%3Ainclude=%2Fcms%2Fsites%2FSite+Name%2Froutes
```

Decoded that is:
```
:include=/cms/sites/Site+Name/routes/cms/frontEnd/fire+/test&:include=/cms/sites/Site+Name/routes/cms/frontEnd/fire+&:include=/cms/sites/Site+Name/routes/cms/frontEnd&:include=/cms/sites/Site+Name/routes/cms&:include=/cms/sites/Site+Name/routes
```

I can add code removing candidates that fail due to this to the PrefixCandidates class like you suggested, but I can't help feel like the issue is somehow deeper, and related to the url encoding in the Request. I just don't know enough about how any of it works to be sure.

I haven't had any luck googling, do you know where the docs on the `:include` are?

**Comment by UFTimmy** [comment]
According to these docs: https://wiki.apache.org/jackrabbit/EncodingAndEscaping

Paths should be escaped in ISO9075. Cobbling together a really rough example, doing that no longer makes Jackrabbit throw errors.

But I cannot seem to get the right combination of ISO9075 and url encoding to have it return results, too.

**Comment by dbu** [comment]
afaik `[]` are special anyways because they are used for indexes when implementing the optional same-name sibling concept of JCR-283. the jackalope implementations do not support those anyways. therefore i think only space is an issue for us. we should completely filter out square brackets from the candidates i think. (from the path, not from query string!)

spaces in urls are a bad thing, but can happen in a cms situation, and when editing and storing works but requests do not, its bad user experience... if you can come up with a solution to make sending requests with spaces in correct encoding, that would be awesome.

**Comment by UFTimmy** [comment]
So I was unable to come up with any solution that allows spaces or brackets to be sent to Jackrabbit successfully. I was able to encode the spaces in ISO9075, but Jackrabbit was not recognizing them as spaces, so it would not match them correctly.

I think the best solution may be to modify PathHelper's `assertValidAbsolutePath`, and add an extra regex that checks for space, left square bracket, and right square bracket at the start or end of every "name". This regex seems to work, at least in limited testing:

`preg_match('~(/[ |\[|\]]|[[ |\|\]]/|[ |\[|\]]$)~', $path)`

What are your thoughts about that?

**Comment by UFTimmy** [comment]
Any thoughts on the above possibility? Would you prefer I narrow the scope and instead do the work when filtering out candidates instead of inside of Jackalope's PathHelper?

**Comment by dbu** [comment]
sorry, missed that one. i think i would prefer to filter that in the candidates here in the bundle. if i understand correctly, at least some of these could be valid paths for the jcr specification and its some sort of encoding/protocol problem either on our end or maybe of jackrabbit itself. if we add it to the PathHelper, it would become hard to remove it if the underlying bug gets fixed.
