### ISSUE TITLE
Bundle stops working with doctrine/persister:^2

### ISSUE THREAD

**Issue by jkabat** [symfony-cmf/routing-bundle#452]
Composer does not lock Common/Persistence doctrine libraries and following line breaks when dependencies are upgraded:

https://github.com/symfony-cmf/routing-bundle/blob/master/src/CmfRoutingBundle.php#L16

Update:

Class Doctrine\Common\Persistence\Mapping\Driver\DefaultFileLocator is part of the Common library only up to version v2.8.1, since v2.9 it is part of the doctrine/persistance library.

Do you have any clever idea how to support both cases?

**Comment by dbu** [comment]
thanks for the heads-up. i fixed this in #453 and tagged 2.4.1

**Comment by jkabat** [comment]
Thank you.
