### ISSUE TITLE
PHP 8.0 compatibility

### ISSUE THREAD

**Issue by ausi** [symfony-cmf/routing-bundle#456]
Are there any plans for adding compatibilty with PHP 8.0?

Would you like me to create a pull request for this?

**Comment by dbu** [comment]
hi, i'd appreciate help, yes. i started with updating some of the dependencies. we need to run tests with phpcr-odm which is upadting in https://github.com/doctrine/phpcr-odm/pull/817 but that is blocked by https://github.com/jackalope/jackalope-doctrine-dbal/pull/373 which is a bit more effort... if you have time to look into the doctrine-dbal upgrades that would be awesome (but i am aware that this is more involved than "just" allowing php 8 ;-) )

**Comment by blankse** [comment]
I see the issue too late :) I created an PR, but yes is blocked by jackalope/jackalope-doctrine-dbal

**Comment by ausi** [comment]
Closed in favor of #457
